// <auto-generated />
namespace Find2Me.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class db_init_identity_tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(db_init_identity_tables));
        
        string IMigrationMetadata.Id
        {
            get { return "201809221312434_db_init_identity_tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
