// <auto-generated />
namespace Find2Me.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class userfollowers_tbl_add : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userfollowers_tbl_add));
        
        string IMigrationMetadata.Id
        {
            get { return "201810231810040_userfollowers_tbl_add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
