// <auto-generated />
namespace Find2Me.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class useradinformation_tbl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(useradinformation_tbl));
        
        string IMigrationMetadata.Id
        {
            get { return "201911011219062_useradinformation_tbl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
