// <auto-generated />
namespace Find2Me.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class userAds_add_image_number : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userAds_add_image_number));
        
        string IMigrationMetadata.Id
        {
            get { return "201908040504122_userAds_add_image_number"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
