//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Find2Me.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Find2Me.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your Email Address - Find2Me.
        /// </summary>
        public static string ConfirmationEmailSubject {
            get {
                return ResourceManager.GetString("ConfirmationEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can create add.
        /// </summary>
        public static string CreateAd {
            get {
                return ResourceManager.GetString("CreateAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string DeleteProfileModalCloseBtn {
            get {
                return ResourceManager.GetString("DeleteProfileModalCloseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE MY PROFILE.
        /// </summary>
        public static string DeleteProfileModalConfirmDeleteBtn {
            get {
                return ResourceManager.GetString("DeleteProfileModalConfirmDeleteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, i&apos;m sure that i want to delete my profile..
        /// </summary>
        public static string DeleteProfileModalConfirmMessage {
            get {
                return ResourceManager.GetString("DeleteProfileModalConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete profile.
        /// </summary>
        public static string DeleteProfileModalHeader {
            get {
                return ResourceManager.GetString("DeleteProfileModalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete your profile and can&apos;t be reestablished..
        /// </summary>
        public static string DeleteProfileModalMessage {
            get {
                return ResourceManager.GetString("DeleteProfileModalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid email address..
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullname.
        /// </summary>
        public static string Fullname {
            get {
                return ResourceManager.GetString("Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name should contain minimum 2 words..
        /// </summary>
        public static string FullNameRegex {
            get {
                return ResourceManager.GetString("FullNameRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid full name..
        /// </summary>
        public static string FullNameRequired {
            get {
                return ResourceManager.GetString("FullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Lookup_Select {
            get {
                return ResourceManager.GetString("Lookup_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred currency.
        /// </summary>
        public static string PreferredCurrency {
            get {
                return ResourceManager.GetString("PreferredCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid currency..
        /// </summary>
        public static string PreferredCurrencyRequired {
            get {
                return ResourceManager.GetString("PreferredCurrencyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred language.
        /// </summary>
        public static string PreferredLanguage {
            get {
                return ResourceManager.GetString("PreferredLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid language..
        /// </summary>
        public static string PreferredLanguageRequired {
            get {
                return ResourceManager.GetString("PreferredLanguageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ads online.
        /// </summary>
        public static string ProfileAdsOnline {
            get {
                return ResourceManager.GetString("ProfileAdsOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A email confirmation link is sent to the provided email address via email. Please confirm your email address..
        /// </summary>
        public static string ProfileConfirmationEmailInfoText {
            get {
                return ResourceManager.GetString("ProfileConfirmationEmailInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your email address. An email has been sent to you..
        /// </summary>
        public static string ProfileConfirmationEmailInfoText2 {
            get {
                return ResourceManager.GetString("ProfileConfirmationEmailInfoText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete profile.
        /// </summary>
        public static string ProfileDeleteProfile {
            get {
                return ResourceManager.GetString("ProfileDeleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ProfileEdit {
            get {
                return ResourceManager.GetString("ProfileEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a username.
        /// </summary>
        public static string ProfileEnterUsernamePlaceHolder {
            get {
                return ResourceManager.GetString("ProfileEnterUsernamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to findings completed.
        /// </summary>
        public static string ProfileFindingsCompleted {
            get {
                return ResourceManager.GetString("ProfileFindingsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow.
        /// </summary>
        public static string ProfileFollow {
            get {
                return ResourceManager.GetString("ProfileFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to followers.
        /// </summary>
        public static string ProfileFollowers {
            get {
                return ResourceManager.GetString("ProfileFollowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow me.
        /// </summary>
        public static string ProfileFollowMe {
            get {
                return ResourceManager.GetString("ProfileFollowMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your full name.
        /// </summary>
        public static string ProfileFullnamePlaceholder {
            get {
                return ResourceManager.GetString("ProfileFullnamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile.
        /// </summary>
        public static string ProfileHeaderText {
            get {
                return ResourceManager.GetString("ProfileHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string ProfileImageCrop_UploadBtnText {
            get {
                return ResourceManager.GetString("ProfileImageCrop_UploadBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRIVATE MESSAGE.
        /// </summary>
        public static string ProfilePrivateMessage {
            get {
                return ResourceManager.GetString("ProfilePrivateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is registered with this email address, through .
        /// </summary>
        public static string ProfileRegisteredEmailInfoText {
            get {
                return ResourceManager.GetString("ProfileRegisteredEmailInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend.
        /// </summary>
        public static string ProfileResendEmail {
            get {
                return ResourceManager.GetString("ProfileResendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to see them here.
        /// </summary>
        public static string ProfileSeeThemHere {
            get {
                return ResourceManager.GetString("ProfileSeeThemHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been here since.
        /// </summary>
        public static string ProfileSince {
            get {
                return ResourceManager.GetString("ProfileSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un Follow.
        /// </summary>
        public static string ProfileUnFollow {
            get {
                return ResourceManager.GetString("ProfileUnFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update profile.
        /// </summary>
        public static string ProfileUpdateProfile {
            get {
                return ResourceManager.GetString("ProfileUpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is invalid..
        /// </summary>
        public static string ProfileUsernameInvalidText {
            get {
                return ResourceManager.GetString("ProfileUsernameInvalidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is valid..
        /// </summary>
        public static string ProfileUsernameValidText {
            get {
                return ResourceManager.GetString("ProfileUsernameValidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile image.
        /// </summary>
        public static string ProfileWizard_ProfileStep1 {
            get {
                return ResourceManager.GetString("ProfileWizard_ProfileStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile info.
        /// </summary>
        public static string ProfileWizard_ProfileStep2 {
            get {
                return ResourceManager.GetString("ProfileWizard_ProfileStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string ProfileWizard_ProfileStep3 {
            get {
                return ResourceManager.GetString("ProfileWizard_ProfileStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR ADS.
        /// </summary>
        public static string ProfileYourAds {
            get {
                return ResourceManager.GetString("ProfileYourAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid sex..
        /// </summary>
        public static string SexRequired {
            get {
                return ResourceManager.GetString("SexRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This English.
        /// </summary>
        public static string SomeLocalisedString {
            get {
                return ResourceManager.GetString("SomeLocalisedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Step1_CropperModalCancelBtn {
            get {
                return ResourceManager.GetString("Step1_CropperModalCancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Step1_CropperModalUpdateBtn {
            get {
                return ResourceManager.GetString("Step1_CropperModalUpdateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop View.
        /// </summary>
        public static string Step1_CropView {
            get {
                return ResourceManager.GetString("Step1_CropView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit image.
        /// </summary>
        public static string Step1_EditProfilePicBtn {
            get {
                return ResourceManager.GetString("Step1_EditProfilePicBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t uploaded any profile picture yet. Please upload a picture first!.
        /// </summary>
        public static string Step1_ImageNotUploadedAlertText {
            get {
                return ResourceManager.GetString("Step1_ImageNotUploadedAlertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload a profile picture..
        /// </summary>
        public static string Step1_ImageRequired {
            get {
                return ResourceManager.GetString("Step1_ImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Image.
        /// </summary>
        public static string Step1_OriginalImage {
            get {
                return ResourceManager.GetString("Step1_OriginalImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile is almost ready..
        /// </summary>
        public static string Step1_ProfileDescriptionText1 {
            get {
                return ResourceManager.GetString("Step1_ProfileDescriptionText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add your profile image to your profile. You will always be able to change it later..
        /// </summary>
        public static string Step1_ProfileDescriptionText2 {
            get {
                return ResourceManager.GetString("Step1_ProfileDescriptionText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile image is shown together with your ad, comments and other things..
        /// </summary>
        public static string Step1_ProfileDescriptionText3 {
            get {
                return ResourceManager.GetString("Step1_ProfileDescriptionText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done! Profile Image is updated successfully!.
        /// </summary>
        public static string Step1_ProfileImageUpdatedInfoText {
            get {
                return ResourceManager.GetString("Step1_ProfileImageUpdatedInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! There was an error while updating Profile Image..
        /// </summary>
        public static string Step1_ProfileImageUpdateFailedInfoText {
            get {
                return ResourceManager.GetString("Step1_ProfileImageUpdateFailedInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload profile image.
        /// </summary>
        public static string Step1_UploadImageBtn {
            get {
                return ResourceManager.GetString("Step1_UploadImageBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile Image.
        /// </summary>
        public static string Step1_UploadImageModalHeading {
            get {
                return ResourceManager.GetString("Step1_UploadImageModalHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is registered with this email address, through.
        /// </summary>
        public static string Step2_ExternalProviderInfoText {
            get {
                return ResourceManager.GetString("Step2_ExternalProviderInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile information.
        /// </summary>
        public static string Step2_ProfileDescriptionText1 {
            get {
                return ResourceManager.GetString("Step2_ProfileDescriptionText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add your profile data. You will always be able to change it later..
        /// </summary>
        public static string Step2_ProfileDescriptionText2 {
            get {
                return ResourceManager.GetString("Step2_ProfileDescriptionText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend Confirmation Link.
        /// </summary>
        public static string Step2_ResendConfirmationLinkBtn {
            get {
                return ResourceManager.GetString("Step2_ResendConfirmationLinkBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A email confirmation link is sent to the provided email address via email. Please confirm your email address..
        /// </summary>
        public static string Step3_EmailConfirmationLinkText {
            get {
                return ResourceManager.GetString("Step3_EmailConfirmationLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to frontpage.
        /// </summary>
        public static string Step3_GoToFrontPageLinkTxt {
            get {
                return ResourceManager.GetString("Step3_GoToFrontPageLinkTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to your profile page.
        /// </summary>
        public static string Step3_GoToProfilePageLinkTxt {
            get {
                return ResourceManager.GetString("Step3_GoToProfilePageLinkTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You.
        /// </summary>
        public static string Step3_ProfileDescriptionText1 {
            get {
                return ResourceManager.GetString("Step3_ProfileDescriptionText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is now ready..
        /// </summary>
        public static string Step3_ProfileDescriptionText2 {
            get {
                return ResourceManager.GetString("Step3_ProfileDescriptionText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to do first?.
        /// </summary>
        public static string Step3_ProfileDescriptionText3 {
            get {
                return ResourceManager.GetString("Step3_ProfileDescriptionText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must contains atleast 5 characters..
        /// </summary>
        public static string UsernameMinLength {
            get {
                return ResourceManager.GetString("UsernameMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid username..
        /// </summary>
        public static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile setup wizard.
        /// </summary>
        public static string Wizard_PageHeading {
            get {
                return ResourceManager.GetString("Wizard_PageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of birth.
        /// </summary>
        public static string YearOfBirth {
            get {
                return ResourceManager.GetString("YearOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid year of birth..
        /// </summary>
        public static string YearOfBirthRequired {
            get {
                return ResourceManager.GetString("YearOfBirthRequired", resourceCulture);
            }
        }
    }
}
